Import Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Load Sample House Price data

In [ ]:
dataset = pd.read_csv('house_price_area.csv')

Separate features and target

In [ ]:
features=dataset.iloc[:,1:].values
target=dataset.iloc[:,0].values

In [ ]:
print(features)
print(target)

[[1500 2002]
 [2200 1995]
 [ 850 2010]
 [3000 2018]
 [4200 2008]
 [1200 1991]
 [1850 2015]
 [2000 2000]
 [ 600 1997]
 [1350 2012]]
[250000 380000 120000 410000 600000 175000 320000 290000  95000 210000]


Split the data set into 80/20 20% test set and 80% training set

In [ ]:
features_train,features_test,target_train,target_test=train_test_split(features,target,test_size=0.2,random_state=42)

Create Instance of Standard Scaler class

In [ ]:
sc=StandardScaler()

Fit the StandardScaler on the features from the training set and transform

In [ ]:
features_train = sc.fit_transform(features_train)

Apply the transform to the test set

In [ ]:
features_test= sc.transform(features_test)

Print the scaled data sets both train and test sets

In [ ]:
    print("Scaled training set:\n", features_train)
    print("Scaled test set:\n", features_test)

Scaled training set:
 [[-0.77017804 -1.92967261]
 [-0.47908713 -0.60302269]
 [ 0.00606439 -0.84423176]
 [-1.1097841   0.36181361]
 [-0.62463258  0.60302269]
 [ 2.14073109  0.12060454]
 [ 0.97636744  1.32664992]
 [-0.13948106  0.9648363 ]]
Scaled test set:
 [[-1.35235986 -1.20604538]
 [ 0.200125   -1.44725445]]
